#!/bin/bash

nosetests TrainsPythonGA/tests/GivenTests.py

nosetests ConferencetrackmanagementPythonGA/tests/PrinterTests.py
nosetests ConferencetrackmanagementPythonGA/tests/SchedulerAppTests.py
nosetests ConferencetrackmanagementPythonGA/tests/SchedulerTests.py

nosetests MerchantsguidetothegalaxyPythonGA/tests/MerchantToolTests.py
nosetests MerchantsguidetothegalaxyPythonGA/tests/ParserTests.py
